# Основные настройки
settings:
  # Показывать ли сообщения о демо-режиме другим игрокам
  # Если true, то все игроки с правом jtdemo.see-messages будут видеть уведомления
  # о входе и выходе из демо-режима
  show-demo-messages: false

  # Добавлять ли префикс к именам игроков в демо-режиме
  # Если true, то игроки в демо-режиме будут иметь префикс перед их именем
  # в чате и списке игроков
  add-demo-prefix: false

  # Префикс для игроков в демо-режиме
  # Этот текст будет добавлен перед именем игрока в демо-режиме
  demo-prefix: "[DEMO] "

  # Сообщение при входе в демо-режим
  demo-enabled-message: "§aДемо-режим включен. Используйте /jtdemo off [пароль] для выключения."

  # Сообщение при выходе из демо-режима
  demo-disabled-message: "§aДемо-режим выключен."

  # Сообщение при неверном пароле
  wrong-password-message: "§cНеверный пароль или демо-режим не активирован."

  # Сообщение о сбросе пароля
  # %player% заменяется на имя игрока
  password-reset-message: "§aПароль для %player% был сброшен на '%default-password%'."

  # Сообщение об установке точки возрождения
  spawn-set-message: "§aТочка возрождения для демо-режима установлена на вашей текущей позиции."

  # Сообщение при перезагрузке плагина
  reload-message: "§aПлагин JTDemo был успешно перезагружен."

  # Пароль по умолчанию (используется при сбросе и для игроков из forced-players)
  default-password: "12345"

  # Интервал проверки изменений файла data.yml (в секундах)
  data-check-interval: 30

# Ограничения в демо-режиме
restrictions:
  # Блоки и взаимодействия
  blocks:
    # Разрешить ли открывать двери
    allow-doors: true

    # Разрешить ли открывать люки
    allow-trapdoors: true

    # Разрешить ли открывать калитки
    allow-gates: false

    # Разрешить ли нажимать кнопки
    allow-buttons: false

    # Разрешить ли нажимать нажимные плиты
    allow-pressure-plates: true

    # Разрешить ли открывать сундуки (только просмотр, без взаимодействия)
    allow-chests: true

    # Разрешить ли открывать шалкеры
    allow-shulker-boxes: false

    # Разрешить ли открывать печи (только просмотр)
    allow-furnaces: true

    # Разрешить ли использовать верстаки
    allow-crafting-tables: false

    # Разрешить ли использовать проигрыватели
    allow-jukeboxes: false

    # Разрешить ли использовать ульи и пчелиные домики
    allow-beehives: false

    # Разрешить ли взаимодействовать с книжными полками
    allow-bookshelves: false

    # Разрешить ли использовать автокрафтеры
    allow-crafters: false

    # Разрешить ли использовать кафедры
    allow-lectern: false

    # Разрешить ли разрушать блоки в мире
    allow-block-breaking: false

  # Игровые механики
  gameplay:
    # Разрешить ли подбирать предметы
    allow-item-pickup: false

    # Разрешить ли использовать инвентарь
    allow-inventory: false

    # Разрешить ли бросать предметы
    allow-item-drop: false

    # Разрешить ли наносить урон другим игрокам
    allow-player-damage: false

    # Разрешить ли наносить урон мобам
    allow-mob-damage: false

    # Сохранять ли максимальный уровень сытости
    preserve-food-level: true

    # Защищать ли от всех типов урона
    invulnerable: false