# Основные настройки
settings:
  # Показывать ли сообщения о демо-режиме другим игрокам
  # Если true, то все игроки с правом jtdemo.see-messages будут видеть уведомления
  # о входе и выходе из демо-режима
  show-demo-messages: false

  # Добавлять ли префикс к именам игроков в демо-режиме
  add-demo-prefix: false

  # Префикс для игроков в демо-режиме
  demo-prefix: "[DEMO] "

  # Пароль по умолчанию (используется при сбросе и для игроков из forced-players)
  default-password: "12345"

  # Интервал проверки файлов (в секундах)
  file-check-interval: 30

# Ограничения в демо-режиме
restrictions:
  # Перемещение и взаимодействие
  movement:
    # Сохранять максимальный уровень сытости
    preserve-food-level: true
    # Защита от всех типов урона
    invulnerable: false
    # Разрешить наносить урон игрокам
    allow-player-damage: false
    # Разрешить наносить урон мобам
    allow-mob-damage: false

  # Инвентарь и предметы
  inventory:
    # Разрешить использовать инвентарь (экипировка, горячая панель)
    allow-inventory-use: false
    # Разрешить подбирать предметы с земли
    allow-item-pickup: false
    # Разрешить выбрасывать предметы
    allow-item-drop: false
    # Разрешить разрушать блоки
    allow-block-breaking: false
    # Разрешить размещать блоки
    allow-block-placing: false

  # Интерактивные блоки
  interactive-blocks:
    # Простые интерактивные блоки
    doors:
      enabled: true         # Разрешить открывать двери
    trapdoors:
      enabled: true         # Разрешить открывать люки
    gates:
      enabled: false        # Разрешить открывать калитки
    buttons:
      enabled: false        # Разрешить нажимать кнопки
    pressure-plates:
      enabled: true         # Разрешить нажимать нажимные плиты

    # Контейнеры и рабочие блоки
    chests:
      open: true            # Разрешить открывать сундуки и бочки
      take-items: false     # Разрешить брать предметы из сундуков и бочек
    shulker-boxes:
      open: false           # Разрешить открывать шалкер-боксы
      take-items: false     # Разрешить брать предметы из шалкер-боксов
    furnaces:
      open: true            # Разрешить открывать печи
      take-items: false     # Разрешить брать предметы из печей
    crafting-tables:
      enabled: false        # Разрешить использовать верстаки
    crafters:
      enabled: false        # Разрешить использовать автокрафтеры

    # Другие интерактивные блоки
    jukeboxes:
      enabled: false        # Разрешить использовать проигрыватели
    beehives:
      enabled: false        # Разрешить взаимодействовать с ульями
    bookshelves:
      enabled: false        # Разрешить взаимодействовать с книжными полками
    lecterns:
      enabled: false        # Разрешить использовать кафедры